- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: JJTechOregon
    region: us-east-2
    image: ami-02f147dfb8be58a10
    id: "web-app"
    sec_group: sg-0fd2815209cd54520

  tasks:


    - name: Provisioning EC2 instances
      block:

      - name: Provision instance(s)
        ec2:
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group_id: "{{ sec_group }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
